spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: sa
    password:


  sql:
    init:
      mode: never

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
